### ISSUE TITLE
Hi Joniii

### ISSUE THREAD

**Issue by 4ndriH** [Nighmared/discord-bot#30]
Your bot seems to have issues when I am attempting to create a meme. The text is for some odd reason unreadable which deeply troubles me. As the meme would have been exquisite.
I used the following text with the big_brain template

> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin dolor lacus, pretium fermentum vehicula at, tempor sit amet odio. Nunc cursus hendrerit nulla. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce tempus nisi eu commodo aliquam. Curabitur nec interdum nisi. Maecenas non orci auctor, fermentum elit sit amet, mattis nulla. Aliquam tincidunt dignissim orci, id malesuada velit fringilla ut.
> 
> Sed elit ex, fermentum sed ultricies vel, tempus nec neque. Aenean et elementum metus. Proin consequat quam nec mi finibus lobortis. Aliquam sit amet neque purus. Curabitur et volutpat mi. Curabitur hendrerit tortor eget commodo dapibus. Aliquam lobortis et risus sit amet aliquam. Suspendisse potenti. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut finibus ante. Nullam vulputate pretium urna auctor molestie. Sed facilisis dolor in tincidunt condimentum. Nunc vulputate ipsum in risus aliquam, non bibendum justo eleifend. Duis luctus, magna sed blandit pharetra, orci tortor laoreet mi, ut lobortis augue tortor et justo. Duis at arcu a ligula eleifend tempor vitae nec ligula.
> 
> In eu leo ex. Donec at ligula ac dui cursus consequat. Quisque ac massa finibus, tempor nunc mattis, porttitor ex. Mauris rhoncus varius sodales. Ut massa odio, ultricies quis venenatis vel, egestas at eros. Fusce vitae justo at est hendrerit consectetur. Sed vulputate vestibulum ante. In eros quam, tincidunt eget vehicula vitae, iaculis eu neque. Nullam sit amet leo ultricies lorem placerat laoreet ut vitae

I hope it is obvious that this is a critical issue which needs to be addressed immediately!

**Comment by Nighmared** [comment]
Won't be fixed.
Reason:
This is not a "bug" (to be precise not even a bug at all) in the code of this project and could only be fixed by painstakingly adding tons of own (duplicate) templates to imgflip just to be able to control the text boxes
